// Major cities/towns per district, for the checkout city dropdown. Not
// exhaustive (Sri Lanka has thousands of smaller towns) — the checkout form
// falls back to a free-text "Other" option for anything not listed here.
export const SRI_LANKA_CITIES: { district: string; cities: string[] }[] = [
  {
    district: "Colombo",
    cities: [
      "Colombo",
      "Dehiwala-Mount Lavinia",
      "Moratuwa",
      "Sri Jayawardenepura Kotte",
      "Kolonnawa",
      "Kaduwela",
      "Kesbewa",
      "Maharagama",
      "Homagama",
      "Battaramulla",
      "Rajagiriya",
      "Nugegoda",
      "Piliyandala",
      "Boralesgamuwa",
      "Nawala",
      "Malabe",
      "Kottawa",
      "Wellampitiya",
      "Ratmalana",
      "Athurugiriya",
      "Padukka",
      "Hanwella",
      "Avissawella",
    ],
  },
  {
    district: "Gampaha",
    cities: [
      "Gampaha",
      "Negombo",
      "Katunayake",
      "Ja-Ela",
      "Wattala",
      "Kelaniya",
      "Peliyagoda",
      "Minuwangoda",
      "Kadawatha",
      "Ragama",
      "Kiribathgoda",
      "Kandana",
      "Seeduwa",
      "Divulapitiya",
      "Mirigama",
      "Nittambuwa",
      "Veyangoda",
      "Ganemulla",
    ],
  },
  {
    district: "Kalutara",
    cities: [
      "Kalutara",
      "Panadura",
      "Horana",
      "Beruwala",
      "Aluthgama",
      "Bentota",
      "Matugama",
      "Wadduwa",
      "Bandaragama",
      "Ingiriya",
    ],
  },
  {
    district: "Kandy",
    cities: [
      "Kandy",
      "Gampola",
      "Nawalapitiya",
      "Wattegama",
      "Peradeniya",
      "Katugastota",
      "Kundasale",
      "Akurana",
      "Pilimatalawa",
      "Kadugannawa",
      "Digana",
    ],
  },
  {
    district: "Matale",
    cities: ["Matale", "Dambulla", "Galewela", "Ukuwela", "Naula", "Rattota", "Sigiriya"],
  },
  {
    district: "Nuwara Eliya",
    cities: [
      "Nuwara Eliya",
      "Hatton",
      "Talawakele",
      "Nanu Oya",
      "Ginigathhena",
      "Kotagala",
      "Maskeliya",
      "Walapane",
    ],
  },
  {
    district: "Galle",
    cities: [
      "Galle",
      "Ambalangoda",
      "Hikkaduwa",
      "Elpitiya",
      "Baddegama",
      "Habaraduwa",
      "Unawatuna",
      "Koggala",
    ],
  },
  {
    district: "Matara",
    cities: ["Matara", "Weligama", "Akuressa", "Deniyaya", "Dickwella", "Kamburupitiya", "Hakmana"],
  },
  {
    district: "Hambantota",
    cities: [
      "Hambantota",
      "Tangalle",
      "Tissamaharama",
      "Ambalantota",
      "Beliatta",
      "Weeraketiya",
      "Sooriyawewa",
    ],
  },
  {
    district: "Jaffna",
    cities: [
      "Jaffna",
      "Chavakachcheri",
      "Point Pedro",
      "Valvettithurai",
      "Chunnakam",
      "Kopay",
      "Nallur",
      "Kayts",
    ],
  },
  { district: "Kilinochchi", cities: ["Kilinochchi", "Pallai", "Paranthan"] },
  { district: "Mannar", cities: ["Mannar", "Pesalai", "Nanattan", "Madhu"] },
  { district: "Vavuniya", cities: ["Vavuniya", "Nedunkeni", "Cheddikulam"] },
  { district: "Mullaitivu", cities: ["Mullaitivu", "Puthukkudiyiruppu", "Oddusuddan"] },
  {
    district: "Batticaloa",
    cities: ["Batticaloa", "Kattankudy", "Eravur", "Valachchenai", "Kaluwanchikudy", "Chenkalady"],
  },
  {
    district: "Ampara",
    cities: [
      "Ampara",
      "Kalmunai",
      "Akkaraipattu",
      "Sainthamaruthu",
      "Sammanthurai",
      "Dehiattakandiya",
      "Uhana",
      "Pottuvil",
    ],
  },
  {
    district: "Trincomalee",
    cities: ["Trincomalee", "Kinniya", "Kantale", "Muttur", "Nilaveli"],
  },
  {
    district: "Kurunegala",
    cities: [
      "Kurunegala",
      "Kuliyapitiya",
      "Narammala",
      "Wariyapola",
      "Pannala",
      "Mawathagama",
      "Nikaweratiya",
      "Polgahawela",
      "Ibbagamuwa",
      "Melsiripura",
      "Alawwa",
    ],
  },
  {
    district: "Puttalam",
    cities: [
      "Puttalam",
      "Chilaw",
      "Wennappuwa",
      "Marawila",
      "Dankotuwa",
      "Nattandiya",
      "Anamaduwa",
      "Madampe",
    ],
  },
  {
    district: "Anuradhapura",
    cities: [
      "Anuradhapura",
      "Kekirawa",
      "Kebithigollewa",
      "Medawachchiya",
      "Thambuttegama",
      "Mihintale",
      "Galenbindunuwewa",
      "Eppawala",
    ],
  },
  {
    district: "Polonnaruwa",
    cities: ["Polonnaruwa", "Hingurakgoda", "Medirigiriya", "Kaduruwela", "Welikanda"],
  },
  {
    district: "Badulla",
    cities: [
      "Badulla",
      "Bandarawela",
      "Haputale",
      "Welimada",
      "Mahiyanganaya",
      "Passara",
      "Ella",
      "Diyatalawa",
    ],
  },
  {
    district: "Monaragala",
    cities: ["Monaragala", "Wellawaya", "Bibile", "Buttala", "Kataragama", "Medagama"],
  },
  {
    district: "Ratnapura",
    cities: ["Ratnapura", "Balangoda", "Embilipitiya", "Pelmadulla", "Eheliyagoda", "Kuruwita", "Kahawatta"],
  },
  {
    district: "Kegalle",
    cities: ["Kegalle", "Mawanella", "Rambukkana", "Warakapola", "Ruwanwella", "Deraniyagala", "Yatiyantota"],
  },
];

export const ALL_SRI_LANKA_CITIES: string[] = SRI_LANKA_CITIES.flatMap((g) => g.cities);
